[workspace]
members = [
  "crates/*",
  "xtask",
  "benches"
]
default-members = ["crates/*"]

[profile.release]
lto = true

[workspace.package]
version = "0.5.3"
authors = ["Herrington Darkholme <2883231+HerringtonDarkholme@users.noreply.github.com>"]
edition = "2021"
license = "MIT"
documentation = "https://ast-grep.github.io/guide/introduction.html"
homepage = "https://ast-grep.github.io/"
repository = "https://github.com/ast-grep/ast-grep"
rust-version = "1.63"
readme = "README.md"

[workspace.dependencies]
ast-grep-core = { path = "crates/core" }
ast-grep-config = { path = "crates/config" }
ast-grep-dynamic = { path = "crates/dynamic" }
ast-grep-language = { path = "crates/language" }
ast-grep-lsp = { path = "crates/lsp" }

bit-set = { version = "0.5.3" }
ignore = { version = "0.4.20" }
regex = { version = "1.8.1" }
serde = { version = "1.0", features = ["derive"] }
tree-sitter = { version = "0.9.1", package = "tree-sitter-facade-sg" }
thiserror = "1.0.40"
