[package]
publish = false
edition = "2021"
name = "xtask"
version = "0.0.0"
authors = ["Herrington Darkholme"]

[dependencies]
anyhow = "1.0"
serde_json = { version = "1.0.91", features = ["preserve_order"] }
