[package]
publish = false
name = "xtask"
version = "0.0.0"

authors.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
serde_json = { version = "1.0.102", features = ["preserve_order"] }
toml_edit = "0.19.14"
