[package]
name = "ast-grep"
version = "0.3.3"
authors = ["Herrington Darkholme <2883231+HerringtonDarkholme@users.noreply.github.com>"]
edition = "2021"
description = "Search and Rewrite code at large scale using precise AST pattern"
keywords = ["ast", "pattern", "codemod", "search", "rewrite"]
license = "MIT"
repository = "https://github.com/ast-grep/ast-grep"
rust-version = "1.63"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "sg"
path = "src/main.rs"

[dependencies]
ast-grep-core = { version = "0.3.3", path = "../core" }
ast-grep-config = { version = "0.3.3", path = "../config" }
ast-grep-lsp = { version = "0.3.3", path = "../lsp" }
ast-grep-language = { version = "0.3.3", path = "../language" }

ansi_term = "0.12"
atty = "0.2.14"
crossterm = "0.26.0"
inquire = "0.6.1"
anyhow = "1.0"
clap = { version = "4.2.1", features = ["derive"] }
codespan-reporting = "0.11.1"
ignore = "0.4.20"
num_cpus = "1.15.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.21"
serde_json = "1.0.95"
similar = { version = "2.2.1", features = ["inline"] }
tokio = { version = "1", features = ["rt-multi-thread", "io-std"] }

[dev-dependencies]
tempdir = "0.3.7"
assert_cmd = "2.0.10"
predicates = "3.0.2"
