[package]
name = "ast-grep"
version = "0.1.6"
authors = ["Herrington Darkholme <2883231+HerringtonDarkholme@users.noreply.github.com>"]
edition = "2021"
description = "Search and Rewrite code at large scale using precise AST pattern"
keywords = ["ast", "pattern", "codemod", "search", "rewrite"]
license = "MIT"
repository = "https://github.com/ast-grep/ast-grep"
rust-version = "1.63"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "sg"
path = "src/main.rs"

[dependencies]
ast-grep-core = { version = "0.1.6", path = "../core" }
ast-grep-config = { version = "0.1.6", path = "../config" }
ast-grep-lsp = { version = "0.1.6", path = "../lsp" }

ansi_term = "0.12"
anyhow = "1.0"
clap = { version = "4.0.18", features = ["derive"] }
codespan-reporting = "0.11.1"
crossbeam = "0.8"
ignore = "0.4.18"
num_cpus = "1.13.1"
rprompt = "1.0.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.14"
similar = { version = "2.2.0", features = ["inline"] }
tokio = { version = "1", features = ["full"] }

tree-sitter-c = "0.20.2"
tree-sitter-go = "0.19.1"
tree-sitter-html = "0.19.0"
tree-sitter-java = "0.19.0"
tree-sitter-javascript = "0.20.0"
tree-sitter-kotlin = "0.2.11"
tree-sitter-lua = "0.0.13"
tree-sitter-python = "0.20.2"
tree-sitter-rust = "0.20.1"
tree-sitter-swift = "0.3.4"
tree-sitter-typescript="0.20.1"
tree-sitter-c-sharp = { version = "0.20.0", package = "ast-grep-tree-sitter-c-sharp" }
crossterm = "0.25.0"
