[package]
name = "ast-grep-config"
version = "0.1.2"
authors = ["Herrington Darkholme <2883231+HerringtonDarkholme@users.noreply.github.com>"]
edition = "2021"
description = "Search and Rewrite code at large scale using precise AST pattern"
keywords = ["ast", "pattern", "codemod", "search", "rewrite"]
license = "MIT"
repository = "https://github.com/HerringtonDarkholme/ast-grep"
rust-version = "1.63"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["regex"]

[dependencies]
ast-grep-core = { version="0.1.2", path = "../core" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.13"
regex = {version = "1.6.0", optional = true }

[dev-dependencies]
tree-sitter-typescript="0.20.1"
