[package]
name = "ast-grep-dynamic"
version = "0.5.1"
authors = [
  "Herrington Darkholme <2883231+HerringtonDarkholme@users.noreply.github.com>",
]
edition = "2021"
description = "Load tree-sitter dynamic library for ast-grep"
keywords = ["ast", "pattern", "codemod", "search", "rewrite"]
license = "MIT"
repository = "https://github.com/ast-grep/ast-grep"
rust-version = "1.63"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast-grep-core = { version = "0.5.1", path = "../core" }
libloading = "0.8"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.40"
ignore = "0.4.20"
tree-sitter-native = { version = "0.20.10", package = "tree-sitter" }
